### ISSUE TITLE
config.js point to a file that does not exist.

### ISSUE THREAD

**Issue by Remi-Gau** [jasminetan6032/artemis_checklist#1]
Hey @jasminetan6032 

Your `config.js` points to `https://raw.githubusercontent.com/jasminetan6032/artemis_checklist/master/protocols/artemis_schema`.

https://github.com/jasminetan6032/artemis_checklist/blob/f865d2f625ef979b25de6da49a91ab89acb1f9fd/ui-changes/src/config.js#L3

But your protocol file actual adress is: 

`https://raw.githubusercontent.com/jasminetan6032/artemis_checklist/master/protocols/artemis/artemis_schema`.

I think that if you change that, the app should run.

**Comment by jasminetan6032** [comment]
It's fixed and it works! Thank you!
